[build]
target = "bpfel-unknown-none"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = "abort"
incremental = false
codegen-units = 1

[profile.release]
lto = true
panic = "abort"
codegen-units = 1